# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acctstatus',
            options={'verbose_name': '\u8d26\u53f7\u72b6\u6001', 'verbose_name_plural': '\u8d26\u53f7\u72b6\u6001'},
        ),
        migrations.AlterModelOptions(
            name='accttype',
            options={'verbose_name': '\u8d26\u53f7\u7c7b\u578b', 'verbose_name_plural': '\u8d26\u53f7\u7c7b\u578b'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': '\u5730\u533a', 'verbose_name_plural': '\u5730\u533a'},
        ),
        migrations.AlterModelOptions(
            name='usertitle',
            options={'verbose_name': '\u5934\u8854', 'verbose_name_plural': '\u5934\u8854'},
        ),
        migrations.AlterField(
            model_name='acctstatus',
            name='acctst_dec',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8d26\u53f7\u72b6\u6001\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='acctstatus',
            name='acctst_lev',
            field=models.IntegerField(verbose_name='\u8d26\u53f7\u72b6\u6001ID'),
        ),
        migrations.AlterField(
            model_name='accttype',
            name='acct_type_dec',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8d26\u53f7\u7c7b\u578b\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='accttype',
            name='acct_type_lev',
            field=models.IntegerField(verbose_name='\u8d26\u53f7\u7c7b\u578bID'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_dec',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8d26\u53f7\u6240\u5c5e\u5730\u533a\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u8d26\u53f7\u6240\u5c5e\u5730\u533aID'),
        ),
        migrations.AlterField(
            model_name='usertitle',
            name='title_dec',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8d26\u53f7\u5934\u8854\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='usertitle',
            name='title_id',
            field=models.IntegerField(verbose_name='\u8d26\u53f7\u5934\u8854ID'),
        ),
    ]
