# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acctstatus',
            options={'verbose_name': '\u8d26\u53f7\u72b6\u6001', 'verbose_name_plural': '\u8d26\u53f7\u72b6\u6001'},
        ),
        migrations.AlterModelOptions(
            name='accttype',
            options={'verbose_name': '\u8d26\u53f7\u7c7b\u578b', 'verbose_name_plural': '\u8d26\u53f7\u7c7b\u578b'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': '\u5730\u533a', 'verbose_name_plural': '\u5730\u533a'},
        ),
        migrations.AlterModelOptions(
            name='usertitle',
            options={'verbose_name': '\u5934\u8854', 'verbose_name_plural': '\u5934\u8854'},
        ),
    ]
