# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20161109_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acctstatus',
            name='acctst_dec',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8d26\u53f7\u72b6\u6001\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='acctstatus',
            name='acctst_lev',
            field=models.IntegerField(verbose_name='\u8d26\u53f7\u72b6\u6001ID'),
        ),
        migrations.AlterField(
            model_name='accttype',
            name='acct_type_dec',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8d26\u53f7\u7c7b\u578b\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='accttype',
            name='acct_type_lev',
            field=models.IntegerField(verbose_name='\u8d26\u53f7\u7c7b\u578bID'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_dec',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8d26\u53f7\u6240\u5c5e\u5730\u533a\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u8d26\u53f7\u6240\u5c5e\u5730\u533aID'),
        ),
        migrations.AlterField(
            model_name='usertitle',
            name='title_dec',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8d26\u53f7\u5934\u8854\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='usertitle',
            name='title_id',
            field=models.IntegerField(verbose_name='\u8d26\u53f7\u5934\u8854ID'),
        ),
    ]
