# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyRewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('isExchg', models.IntegerField(default=0, verbose_name='\u662f\u5426\u5df2\u9886\u5956')),
                ('exchg_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u9886\u5956\u4eba\u59d3\u540d')),
                ('exchg_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='\u9886\u5956\u4eba\u624b\u673a')),
                ('exchg_addr', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u9886\u5956\u4eba\u5730\u5740')),
                ('addr_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u9886\u5956\u4eba\u90ae\u7f16')),
                ('express_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5feb\u9012\u5355\u53f7')),
                ('express_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5feb\u9012\u516c\u53f8\u540d\u79f0')),
                ('update_ts', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_code', models.CharField(max_length=50, verbose_name='\u5956\u54c1\u7f16\u7801')),
                ('reward_desc', models.CharField(max_length=200, verbose_name='\u5956\u54c1\u63cf\u8ff0')),
                ('reward_cost', models.IntegerField(blank=True, null=True, verbose_name='\u62b5\u6263\u79ef\u5206')),
                ('reward_effdt', models.DateField(verbose_name='\u751f\u6548\u65e5\u671f')),
                ('reward_enddt', models.DateField(verbose_name='\u5931\u6548\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='RewardsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewardstype_code', models.CharField(max_length=50, verbose_name='\u5956\u54c1\u7c7b\u578b\u7f16\u7801')),
                ('rewardstype_desc', models.CharField(max_length=200, verbose_name='\u5956\u54c1\u7c7b\u578b\u63cf\u8ff0')),
            ],
        ),
        migrations.AddField(
            model_name='rewards',
            name='reward_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.RewardsType', verbose_name='\u5956\u54c1\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='myrewards',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.Rewards', verbose_name='\u5956\u54c1'),
        ),
    ]
