# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiontype_code', models.CharField(max_length=50, verbose_name='\u6d3b\u52a8\u7c7b\u578b\u7f16\u7801')),
                ('actiontype_desc', models.CharField(max_length=200, verbose_name='\u6d3b\u52a8\u7c7b\u578b\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u6d3b\u52a8\u7c7b\u578b',
                'verbose_name_plural': '\u6d3b\u52a8\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='Ecards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecardnum', models.CharField(max_length=200, verbose_name='\u5361\u53f7')),
                ('ecardpsw', models.CharField(max_length=200, verbose_name='\u5361\u5bc6')),
                ('isValid', models.BooleanField(verbose_name='\u662f\u5426\u53ef\u7528')),
            ],
            options={
                'verbose_name': '\u5361\u54c1\u6e05\u5355',
                'verbose_name_plural': '\u5361\u54c1\u6e05\u5355',
            },
        ),
        migrations.CreateModel(
            name='EcardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecardtype_code', models.CharField(max_length=50, verbose_name='\u5361\u54c1\u7c7b\u578b\u7f16\u7801')),
                ('ecardtype_desc', models.CharField(max_length=200, verbose_name='\u5361\u54c1\u7c7b\u578b\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u5361\u54c1\u7c7b\u578b',
                'verbose_name_plural': '\u5361\u54c1\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='MyRewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='\u4e2d\u5956\u8d26\u53f7')),
                ('reward_dt', models.DateField(blank=True, null=True, verbose_name='\u4e2d\u5956\u65e5\u671f')),
                ('isExchg', models.BooleanField(verbose_name='\u662f\u5426\u5df2\u9886\u5956')),
                ('exchg_dt', models.DateField(blank=True, null=True, verbose_name='\u5151\u6362/\u9886\u5956\u65e5\u671f')),
                ('exchg_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u9886\u5956\u4eba\u59d3\u540d')),
                ('exchg_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='\u9886\u5956\u4eba\u624b\u673a')),
                ('exchg_addr', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u9886\u5956\u4eba\u5730\u5740')),
                ('addr_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u9886\u5956\u4eba\u90ae\u7f16')),
                ('express_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5feb\u9012\u5355\u53f7')),
                ('express_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5feb\u9012\u516c\u53f8\u540d\u79f0')),
                ('ecardnum', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u865a\u62df\u5361\u54c1\u5361\u53f7')),
                ('update_ts', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4e2d\u5956\u7eaa\u5f55',
                'verbose_name_plural': '\u4e2d\u5956\u7eaa\u5f55',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixnum', models.CharField(max_length=11, verbose_name='\u624b\u673a\u53f7\u524d\u4e09\u4f4d')),
                ('prefixnumtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.EcardType', verbose_name='\u5361\u54c1\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u8fd0\u8425\u5546\u624b\u673a\u53f7\u6bb5',
                'verbose_name_plural': '\u8fd0\u8425\u5546\u624b\u673a\u53f7\u6bb5',
            },
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_code', models.CharField(max_length=50, verbose_name='\u5956\u54c1\u7f16\u7801')),
                ('reward_desc', models.CharField(max_length=200, verbose_name='\u5956\u54c1\u63cf\u8ff0')),
                ('reward_cost', models.IntegerField(blank=True, null=True, verbose_name='\u62b5\u6263\u79ef\u5206')),
                ('reward_effdt', models.DateField(verbose_name='\u751f\u6548\u65e5\u671f')),
                ('reward_enddt', models.DateField(verbose_name='\u5931\u6548\u65e5\u671f')),
                ('reward_nums', models.IntegerField(verbose_name='\u5956\u54c1\u603b\u6570')),
                ('reward_left', models.IntegerField(verbose_name='\u5956\u54c1\u5269\u4f59\u6570')),
                ('reward_rmk', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u5956\u54c1\u5907\u6ce8')),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.ActionType', verbose_name='\u6d3b\u52a8\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u5956\u54c1',
                'verbose_name_plural': '\u5956\u54c1',
            },
        ),
        migrations.CreateModel(
            name='RewardsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewardstype_code', models.CharField(max_length=50, verbose_name='\u5956\u54c1\u7c7b\u578b\u7f16\u7801')),
                ('rewardstype_desc', models.CharField(max_length=200, verbose_name='\u5956\u54c1\u7c7b\u578b\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u5956\u54c1\u7c7b\u578b',
                'verbose_name_plural': '\u5956\u54c1\u7c7b\u578b',
            },
        ),
        migrations.AddField(
            model_name='rewards',
            name='reward_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.RewardsType', verbose_name='\u5956\u54c1\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='myrewards',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.Rewards', verbose_name='\u5956\u54c1'),
        ),
        migrations.AddField(
            model_name='ecards',
            name='ecardtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.EcardType', verbose_name='\u5361\u54c1\u7c7b\u578b'),
        ),
    ]
