# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myrewards',
            options={'verbose_name': '\u4e2d\u5956\u7eaa\u5f55', 'verbose_name_plural': '\u4e2d\u5956\u7eaa\u5f55'},
        ),
        migrations.AlterModelOptions(
            name='rewards',
            options={'verbose_name': '\u5956\u54c1', 'verbose_name_plural': '\u5956\u54c1'},
        ),
        migrations.AlterModelOptions(
            name='rewardstype',
            options={'verbose_name': '\u5956\u54c1\u7c7b\u578b', 'verbose_name_plural': '\u5956\u54c1\u7c7b\u578b'},
        ),
        migrations.RemoveField(
            model_name='myrewards',
            name='user_id',
        ),
        migrations.AddField(
            model_name='myrewards',
            name='username',
            field=models.CharField(default=None, max_length=50, verbose_name='\u4e2d\u5956\u8d26\u53f7'),
            preserve_default=False,
        ),
    ]
