# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 00:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_base', models.IntegerField(verbose_name='\u6982\u7387\u57fa\u6570')),
                ('rwd_s_idx', models.IntegerField(verbose_name='\u6982\u7387\u8303\u56f4\u5f00\u59cb\u6570')),
                ('rwd_e_idx', models.IntegerField(verbose_name='\u6982\u7387\u8303\u56f4\u7ed3\u675f\u6570')),
            ],
            options={
                'verbose_name': '\u6d3b\u52a8\u914d\u7f6e',
                'verbose_name_plural': '\u6d3b\u52a8\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_code', models.CharField(max_length=50, verbose_name='\u6d3b\u52a8\u7f16\u7801')),
                ('action_desc', models.CharField(max_length=200, verbose_name='\u6d3b\u52a8\u63cf\u8ff0')),
                ('is_cur_action', models.BooleanField(verbose_name='\u662f\u5426\u5f53\u524d\u6d3b\u52a8')),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.ActionType', verbose_name='\u6d3b\u52a8\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u6d3b\u52a8',
                'verbose_name_plural': '\u6d3b\u52a8',
            },
        ),
        migrations.CreateModel(
            name='LotteryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_ts', models.DateTimeField(auto_now_add=True, verbose_name='\u62bd\u5956\u65f6\u95f4')),
                ('random_num', models.IntegerField(verbose_name='\u62bd\u5956\u968f\u673a\u6570')),
                ('opt_remark', models.CharField(max_length=200, verbose_name='\u5907\u6ce8')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8d26\u53f7')),
            ],
            options={
                'verbose_name': '\u62bd\u5956\u65e5\u5fd7',
                'verbose_name_plural': '\u62bd\u5956\u65e5\u5fd7',
            },
        ),
        migrations.AddField(
            model_name='actionconf',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.Actions', verbose_name='\u6d3b\u52a8'),
        ),
        migrations.AddField(
            model_name='actionconf',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.Rewards', verbose_name='\u5956\u54c1'),
        ),
    ]
