# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_auto_20161109_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrewards',
            name='reward_dt',
            field=models.DateField(blank=True, null=True, verbose_name='\u4e2d\u5956\u65f6\u95f4'),
        ),
    ]
