# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_auto_20161217_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionconf',
            name='rw_order',
            field=models.IntegerField(default=1, verbose_name='\u5956\u54c1\u6392\u5e8f'),
            preserve_default=False,
        ),
    ]
