# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-23 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0006_actions_create_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewards',
            name='reward_cost_ori',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u6253\u62c6\u524d\u62b5\u6263\u79ef\u5206'),
        ),
        migrations.AddField(
            model_name='rewards',
            name='reward_pic',
            field=models.ImageField(default='static/images/smarket/default.jpg', upload_to='static/images/smarket/', verbose_name='\u5956\u54c1\u56fe\u7247'),
        ),
    ]
