# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-25 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_auto_20161223_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewards',
            name='isphonecard',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u624b\u673a\u5145\u503c\u5361'),
        ),
    ]
