# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-25 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0008_rewards_isphonecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='reward_pic',
            field=models.ImageField(default='static/images/smarket/default.jpg', upload_to='smarket/', verbose_name='\u5956\u54c1\u56fe\u7247'),
        ),
    ]
