# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 15:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u516c\u544a\u6807\u9898')),
                ('anncm', models.TextField(verbose_name='\u516c\u544a\u5185\u5bb9')),
                ('is_curanncm', models.BooleanField(default=False, verbose_name='\u662f\u5426\u8bbe\u4e3a\u5f53\u524d\u516c\u544a')),
                ('create_ts', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('update_ts', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8d26\u53f7')),
            ],
            options={
                'verbose_name': '\u516c\u544a',
                'verbose_name_plural': '\u516c\u544a',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctgy_code', models.CharField(max_length=50, verbose_name='\u677f\u5757\u7c7b\u578b\u7f16\u7801')),
                ('ctgy_desc', models.CharField(max_length=200, verbose_name='\u677f\u5757\u7c7b\u578b\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u677f\u5757\u7c7b\u578b',
                'verbose_name_plural': '\u677f\u5757\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='Cbbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u4e3b\u9898')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('create_ts', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('update_ts', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('viewers', models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u6570')),
                ('comnts', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u6570')),
                ('priority', models.IntegerField(default=0, verbose_name='\u4f18\u5148\u7ea7')),
                ('wanted_score', models.IntegerField(default=0, verbose_name='\u60ac\u8d4f\u79ef\u5206')),
                ('wanted_ovddt', models.DateTimeField(blank=True, null=True, verbose_name='\u60ac\u8d4f\u8fc7\u671f\u65f6\u95f4')),
                ('tips_score', models.IntegerField(default=0, verbose_name='\u6253\u8d4f\u79ef\u5206')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Category', verbose_name='\u6240\u5c5e\u677f\u5757')),
            ],
            options={
                'verbose_name': '\u793e\u533a\u4e3b\u9898',
                'verbose_name_plural': '\u793e\u533a\u4e3b\u9898',
            },
        ),
        migrations.CreateModel(
            name='CbbsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbbsctgy_code', models.CharField(max_length=50, verbose_name='\u4e3b\u9898\u7c7b\u578b\u7f16\u7801')),
                ('cbbsctgy_desc', models.CharField(max_length=200, verbose_name='\u4e3b\u9898\u7c7b\u578b\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u4e3b\u9898\u7c7b\u578b',
                'verbose_name_plural': '\u4e3b\u9898\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='CbbsTips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='\u79ef\u5206')),
                ('op_ts', models.DateTimeField(auto_now_add=True, verbose_name='\u6253\u8d4f\u65f6\u95f4')),
                ('cbbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Cbbs', verbose_name='\u4e3b\u9898')),
            ],
            options={
                'verbose_name': '\u6253\u8d4f\u65e5\u5fd7',
                'verbose_name_plural': '\u6253\u8d4f\u65e5\u5fd7',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('create_ts', models.DateTimeField(auto_now_add=True, verbose_name='\u8bc4\u8bba\u65f6\u95f4')),
                ('favors', models.IntegerField(default=0, verbose_name='\u652f\u6301\u6570')),
                ('kicks', models.IntegerField(default=0, verbose_name='\u53cd\u5bf9\u6570')),
                ('is_reward', models.BooleanField(default=False, verbose_name='\u662f\u5426\u83b7\u8d4f')),
                ('reward_dt', models.DateTimeField(blank=True, null=True, verbose_name='\u83b7\u8d4f\u65f6\u95f4')),
                ('reward_score', models.IntegerField(default=0, verbose_name='\u83b7\u8d4f\u79ef\u5206')),
                ('cbbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Cbbs', verbose_name='\u4e3b\u9898')),
                ('ref_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Comments', verbose_name='\u5f15\u7528\u8bc4\u8bba')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8d26\u53f7')),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba',
                'verbose_name_plural': '\u8bc4\u8bba',
            },
        ),
        migrations.AddField(
            model_name='cbbstips',
            name='comnt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Comments', verbose_name='\u8bc4\u8bba'),
        ),
        migrations.AddField(
            model_name='cbbstips',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='\u6253\u8d4f\u8d26\u53f7'),
        ),
        migrations.AddField(
            model_name='cbbstips',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='\u83b7\u8d4f\u8d26\u53f7'),
        ),
        migrations.AddField(
            model_name='cbbs',
            name='cbbsctgy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.CbbsCategory', verbose_name='\u4e3b\u9898\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='cbbs',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8d26\u53f7'),
        ),
    ]
