# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 11:26
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20161130_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbbs',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='\u5185\u5bb9'),
        ),
    ]
