# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20161130_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='ref_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Comments', verbose_name='\u5f15\u7528\u8bc4\u8bba'),
        ),
    ]
