# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0005_auto_20161204_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='CbbsUserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_ts', models.DateTimeField(auto_now_add=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Comments', verbose_name='\u6d89\u53ca\u56de\u590d')),
            ],
            options={
                'verbose_name': '\u793e\u533a\u7528\u6237\u65e5\u5fd7',
                'verbose_name_plural': '\u793e\u533a\u7528\u6237\u65e5\u5fd7',
            },
        ),
        migrations.CreateModel(
            name='CUserOptCtgy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_code', models.CharField(max_length=50, verbose_name='\u793e\u533a\u7528\u6237\u65e5\u5fd7\u7c7b\u578b\u7f16\u7801')),
                ('opt_desc', models.CharField(max_length=200, verbose_name='\u793e\u533a\u7528\u6237\u65e5\u5fd7\u7c7b\u578b\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u793e\u533a\u7528\u6237\u65e5\u5fd7\u7c7b\u578b',
                'verbose_name_plural': '\u793e\u533a\u7528\u6237\u65e5\u5fd7\u7c7b\u578b',
            },
        ),
        migrations.AddField(
            model_name='cbbsuserlog',
            name='optctgy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.CUserOptCtgy', verbose_name='\u7528\u6237\u65e5\u5fd7\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='cbbsuserlog',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Cbbs', verbose_name='\u6d89\u53ca\u4e3b\u9898'),
        ),
        migrations.AddField(
            model_name='cbbsuserlog',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8d26\u53f7'),
        ),
    ]
