# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20161205_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbbsuserlog',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Comments', verbose_name='\u6d89\u53ca\u56de\u590d'),
        ),
        migrations.AlterField(
            model_name='cbbsuserlog',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Cbbs', verbose_name='\u6d89\u53ca\u4e3b\u9898'),
        ),
    ]
