# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UScoreLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='\u8d26\u53f7')),
                ('score', models.IntegerField(verbose_name='\u5165\u8d26\u79ef\u5206')),
                ('opby', models.CharField(max_length=50, verbose_name='\u64cd\u4f5c\u8d26\u53f7')),
                ('remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u5907\u6ce8')),
                ('update_ts', models.DateTimeField(auto_now=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u79ef\u5206\u64cd\u4f5c\u5386\u53f2',
                'verbose_name_plural': '\u7528\u6237\u79ef\u5206\u64cd\u4f5c\u5386\u53f2',
            },
        ),
        migrations.CreateModel(
            name='UScoreOpType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=50, verbose_name='\u64cd\u4f5c\u7c7b\u578b\u7f16\u7801')),
                ('type_desc', models.CharField(max_length=200, verbose_name='\u64cd\u4f5c\u7c7b\u578b\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u79ef\u5206\u64cd\u4f5c\u7c7b\u578b',
                'verbose_name_plural': '\u7528\u6237\u79ef\u5206\u64cd\u4f5c\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='UScoreOv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='\u8d26\u53f7')),
                ('days_in_a_row', models.IntegerField(default=0, verbose_name='\u8fde\u7eed\u7b7e\u5230\u5929\u6570')),
                ('days_in_month', models.IntegerField(default=0, verbose_name='\u672c\u6708\u7b7e\u5230\u5929\u6570')),
                ('days_in_year', models.IntegerField(default=0, verbose_name='\u672c\u5e74\u7b7e\u5230\u5929\u6570')),
                ('accum_score', models.IntegerField(default=0, verbose_name='\u7b7e\u5230\u7d2f\u8ba1\u79ef\u5206')),
                ('last_chkin_dt', models.DateField(auto_now=True, verbose_name='\u4e0a\u6b21\u7b7e\u5230\u65e5\u671f')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u79ef\u5206\u7edf\u8ba1\u9884\u89c8',
                'verbose_name_plural': '\u7528\u6237\u79ef\u5206\u7edf\u8ba1\u9884\u89c8',
            },
        ),
        migrations.AddField(
            model_name='uscorelog',
            name='usot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.UScoreOpType', verbose_name='\u64cd\u4f5c\u7c7b\u578b'),
        ),
    ]
