# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_uscoreov_last_chkin_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uscoreov',
            name='last_chkin_dt',
            field=models.DateField(verbose_name='\u4e0a\u6b21\u7b7e\u5230\u65e5\u671f'),
        ),
    ]
